import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
     
      </head>
      <body className={`dark:bg-black text-white ${inter.className}`}> 
      <MantineProvider >{children}</MantineProvider>
        <Navbar />
        
        </body>
    </html>
  );
}
